FBE-1442: Update MAPI /v1/event/purchase documentation for addition of referralCode parameter.
friendbuy/slate pull request #17
Opened 2021-04-27 17:06 UTC by dhull

* Update README.md to describe how Friendbuy uses Slate.

* Update MAPI /v1/event/purchase documentation for addition of referralCode parameter.

2021-05-03 18:32 UTC, britainjs requested changes
One note. Looks good otherwise.

2021-05-03 18:32 UTC, britainjs commented on source/includes/_merchant_api.md
> +When you submit a purchase using the Friendbuy Merchant API, you must submit a unique order id, a customer id, a purchase amount, and the currency the purchase was in. We strongly recommend also pass
I believe customer id is an optional property since a lot of merchants support guest checkout.

2021-05-04 15:58 UTC, dhull commented on source/includes/_merchant_api.md
> +When you submit a purchase using the Friendbuy Merchant API, you must submit a unique order id, a customer id, a purchase amount, and the currency the purchase was in. We strongly recommend also pass
I was updating this according to what the openapi.yaml says.

```yaml
    purchaseEventRequest:
      type: object
      required:
        - orderId
        - customerId
        - amount
        - currency
```

2021-05-06 20:42 UTC, britainjs commented on source/includes/_merchant_api.md
> +When you submit a purchase using the Friendbuy Merchant API, you must submit a unique order id, a customer id, a purchase amount, and the currency the purchase was in. We strongly recommend also pass
I did some more poking around and it doesn't actually seem like there is a way to track purchases with an email but no customer id, either through the mapi or through javascript. https://kibana.fbot.me/_plugin/kibana/goto/7b4f9583fbb80d7f76e937054ae45bf4 

Definitely out of the scope for this project, but something we should address.

2021-05-06 23:10 UTC, dhull commented on source/includes/_merchant_api.md
> +When you submit a purchase using the Friendbuy Merchant API, you must submit a unique order id, a customer id, a purchase amount, and the currency the purchase was in. We strongly recommend also pass
I have reverted the change to say that customerId is required. We still need to update the openapi.yaml for that change.

2021-05-07 20:30 UTC, britainjs approved these changes

2021-05-07 20:58 UTC, merged